declare var instruments: [
    "Accordian",
    "Accoustic guitar",
    "Bagpipe",
    "Banjo",
    "Bass guitar",
    "Bells",
    "Bongo drum",
    "Bugle",
    "Cello",
    "Clarinet",
    "Cornet",
    "Didgeridoo",
    "Double bass",
    "Drum kit",
    "Electric guitar",
    "Flute",
    "French horn",
    "Glockenspiel",
    "Gong",
    "Harmonica",
    "Harp",
    "Keyboard",
    "Mandolin",
    "Maracas",
    "Marimba",
    "Oboe",
    "Organ",
    "Pan flute",
    "Piano",
    "Purcussion",
    "Recorder",
    "Saxophone",
    "Sitar",
    "Tambourine",
    "Timpani",
    "Triangle",
    "Trombone",
    "Trumpet",
    "Tuba",
    "Ukulele",
    "Vibraphone",
    "Violin",
    "Xylophone",
    "Zither",
    "Other"
]


declare var genres: [
    "A cappella",
    "Acoustic",
    "Afrobeat",
    "Alternatice rock",
    "Ambient music",
    "American folk",
    "Americana",
    "Avant-garde",
    "Bachata",
    "Ballet",
    "Barbershop",
    "Baroque",
    "Big band",
    "Bluegrass",
    "Blues",
    "Boogie",
    "Boy band",
    "Cabaret",
    "Carol",
    "Celtic",
    "Chamber music",
    "Christian",
    "Classical",
    "Contemporary",
    "Country",
    "Dance music",
    "Death metal",
    "Disco",
    "Doo-wop",
    "Dream pop",
    "Dub music",
    "Electronic",
    "Emo",
    "Experimental",
    "Flamenco",
    "Folk",
    "Funk",
    "Girl group",
    "Gothic",
    "Gregorian chant",
    "Hard rock",
    "Hip hop",
    "House music",
    "Indie",
    "Industrial",
    "Jazz",
    "Jazz-funk",
    "Jewish",
    "K-pop",
    "Latin",
    "Lo-fi",
    "Mariachi",
    "Mass",
    "Meditation music",
    "Metal",
    "Motown",
    "Neoclassical",
    "New wave",
    "Opera",
    "Polka",
    "Pop",
    "Psychadelic",
    "Punk",
    "Ragga",
    "Rave music",
    "Reggae",
    "Religious",
    "Renaissance",
    "RnB",
    "Rock",
    "Salsa",
    "Samba",
    "Sea shanty",
    "Ska",
    "Soul",
    "Soundtrack",
    "Synth-pop",
    "Techno",
    "Trap",
    "Tropical",
    "Other"
]

declare var experiences: [
    "Just starting",
    "Beginner",
    "Intermediate",
    "Advanced",
    "Expert"
]