import Head from 'next/head'
import Search from './search'
import About from './about'

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/jam-jar.jpg" />
        <link rel="stylesheet" href="../node_modules/@chatscope/chat-ui-kit-styles/dist/default/styles.min.css"/>
      </Head>
      <main>
        <About />
      </main>
    </>
  )
}
