import { useAuthUser, withAuthUser } from 'next-firebase-auth'
import Router from 'next/router'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { Button } from 'react-bootstrap'
import { sendEmailVerification } from 'firebase/auth'


function EmailVerification() {
  const [showMessage, setShowMessage] = useState(false);
  const [emailSent, setEmailSent] = useState(false);
  const [user, setUser] = useState<any>({});

  const AuthUser = useAuthUser();
  useEffect(() => {
    if(AuthUser.id !== null){
      setUser(AuthUser.firebaseUser);
      if(!AuthUser.emailVerified){
        setShowMessage(true);
        AuthUser.signOut();
      }
      else{
        verifiedEmail();
      }
    }
  }, [AuthUser])
  
  function verifiedEmail(){
    Router.push('/login');
  }

  function sendEmail(){
    sendEmailVerification(user)
    .then(() => {
      setEmailSent(true);
    });
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/jam-jar.jpg" />
      </Head>
      <main>
        { emailSent &&
          <h2>Verification email has been sent!</h2>
        }
        { showMessage &&
        <>
        <h1>
          Please Verify Your Email
        </h1>
        <Button onClick={verifiedEmail}>I verified my email</Button>
        <Button onClick={sendEmail}>Resend Email Verification Link</Button>
        </>
        }
        {
          !showMessage &&
          <>
          <h1>Waiting for login credetials...</h1>
          <Button onClick={verifiedEmail}>Click here to login</Button>
          </>
        }
      </main>
    </>
  )
}

export default withAuthUser({})(EmailVerification)
